version: '3.4'

services:
  
  vsdockerwebapp:
    image: ${DOCKER_REGISTRY-}vsdockerwebapp
    build:
      context: .
      dockerfile: VSDockerWebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5551:80"
      - "55551:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  vsdockerwebapp-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:vsdockerwebapp"
    command: ["./daprd",
      "-app-id", "VsDockerWebApp",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/blog-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - vsdockerwebapp

  supportapi:
    image: ${DOCKER_REGISTRY-}supportapi
    build:
      context: .
      dockerfile: SupportApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5552:80"
      - "55552:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - redis

  supportapi-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:supportapi"
    command: ["./daprd",
      "-app-id", "supportapi",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/blog-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    depends_on:
      - supportapi
  
  redis:
    image: redis:alpine
    ports:
      - "4379:6379"

  dapr-placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "40000:50000"    