apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blog-secretstore
  namespace: blog
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/blog-secrets.json
    - name: nestedSeparator
      value: "."
